# Generated by Django 2.2.6 on 2020-05-29 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PantryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('quantity_min', models.IntegerField()),
                ('quantity_now', models.IntegerField()),
            ],
        ),
    ]
