# Generated by Django 2.2.6 on 2020-05-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry_trackr', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
